### ISSUE TITLE
Enhancement request: more complex table examples

### ISSUE THREAD

**Issue by bluebob** [baliance/gooxml#104]
## Description
Could you please update/extend the table example to show more complex tables, e.g. cell highlight use, left/right/centre alignment. I'm particularly interested in control of horizontal alignment - and centering headings seems to be a non-trivial task to configure.

## Expected Behavior
n/a - documentation update

## Actual Behavior
n/a - documentation update

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by tbaliance** [comment]
@bluebob Pull latest and check out the tables example and see if that is what you wanted.  Feel free to re-open this issue if it didn't cover your use case.
