### ISSUE TITLE
spreadsheet: SaveToFile broken

### ISSUE THREAD

**Issue by alfalfalfa** [baliance/gooxml#107]
## Description
can not open an output file by loading an existing file
(Excel for Mac ver 15.29.1)

`// empty.xlsx was created in this way (Excel -> New -> Save)`
` wb, _ := spreadsheet.Open("empty.xlsx")`
`// it's broken`
` wb.SaveToFile("empty_out.xlsx")`

[empty.xlsx](https://github.com/baliance/gooxml/files/1357710/empty.xlsx)

**Comment by tbaliance** [comment]
@alfalfalfa  This should be fixed now. We were round-tripping some non-standard content on the Workbook, but it looks like Excel wants some non-standard attributes round-tripped as well.  It works fine just dropping the non-standard content for now.

In case you're interested, this is the content that is dropped. My guess it Excel uses it for something like the initial path in the file open or file save as dialog when editing the workbook.

      <mc:AlternateContent xmlns:mc="http://schemas.openxmlformats.org/markup-compatibil  ity/2006">
          <mc:Choice Requires="x15">
              <x15ac:absPath url="/Users/takuma/Projects/30_A3/a3_server/" xmlns:x15ac="  http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac" />
          </mc:Choice>
      </mc:AlternateContent>
