### ISSUE TITLE
Access to existing headers & footers

### ISSUE THREAD

**Issue by freb** [baliance/gooxml#116]
## Description

My approach with another library has been to create a document to act as a template that included as much of the content and formatting as possible, overwriting what I could and adding content where I had to.

I am am attempting to overwrite the content of an existing header in a document instead of adding a new one from scratch, but there doesn't appear to be a way to access to the headers and footers on the document struct like you can with the `Paragraphs` method, for instance.

## Expected Behavior

The ability to access headers and footers in an existing document.

## Actual Behavior

I cannot figure out how to edit existing headers and footers as the `headers` and `footers` fields on `Document` are not exported.

As I understand it, headers and footers are stored differently than other aspects of the XML document, so I'm just wondering if this is a work in progress or if I just missed something simple.

**Comment by tbaliance** [comment]
@freb You didn't miss any capability, I never needed to do that and didn't think to export it. 

I've got a PR up that exports Headers/Footers as well as adding RemoveParagraph/Clear methods on them to support removing individual paragraphs or clearing all content within the header.  It should be merged in the next few minutes as soon as it passes CI. If you notice any other capability missing, please let me know.

**Comment by freb** [comment]
Awesome! I'll take a look.

The only other thing I had noticed so far were the lack of update methods on runs, but just today I noticed you added those with the remove/clear methods you mentioned. That's actually what made me look to see if there was any change to the header/footer access. But really, dropping down to `.X()` wasn't that bad and its really nice to be able to do that.

Thanks again!
Jeff

**Comment by mytea003** [comment]
> Awesome! I'll take a look.
> 
> The only other thing I had noticed so far were the lack of update methods on runs, but just today I noticed you added those with the remove/clear methods you mentioned. That's actually what made me look to see if there was any change to the header/footer access. But really, dropping down to `.X()` wasn't that bad and its really nice to be able to do that.
> 
> Thanks again!
> Jeff

hello,Have you found the problem of changing the original header in the document? I also encountered the same problem, and during the replacement process, the document's watermark disappeared.
