### ISSUE TITLE
Adding internal links

### ISSUE THREAD

**Issue by freb** [baliance/gooxml#126]
I'm looking to add internal links in a document. I see the functionality for adding HyperLinks, but that appears to only be for external URLs. I'm looking for the functionality of creating a hyperlink to a "Place in this document" as is available from within word.

My use case is adding links to appendices into the body of my document (e.g. "see <appendix A>"). The text containing the link would most likely be a run that points to a heading.

**Comment by tbaliance** [comment]
I tested and Word inserts a bookmark at the destination (heading, etc.) and then references it from the hyperlink.  Please let me know if you run into any issues with the implementation.

**Comment by freb** [comment]
Code works perfectly. I haven't decided if I'm going to stick with my current method of filling in sections of an already populated and formatted document, or create the document from scratch. Once I start playing with filling in my current template, I may discover I need more functions for discovering and iterating existing objects in the document, such as existing bookmarks, tables, etc. I'll open new issues for anything I find missing there.

Thanks for the quick update!

**Comment by tbaliance** [comment]
Sure thing!  I've used both of those methods, and there are definite tradeoffs to each.

Lately, I've preferred constructing documents entirely in code.  It's a larger investment in time up front, but there's something nice about having it all done that way. In the end, it may just be personal preference.
