### ISSUE TITLE
Helper function for paragraph Indentation level

### ISSUE THREAD

**Issue by freb** [baliance/gooxml#136]
Any interest in adding a convenience function for setting paragraph indentation level?

Its really not too bad using `.X()`, but thought I'd raise it in case you're interested in which cases people need to use `.X`.

Here is what I did and seems to work fine:

~~~go
numpr := wml.NewCT_NumPr()
lvl := wml.NewCT_DecimalNumber()
lvl.ValAttr = int64(listLevel) // listLevel was int
numpr.Ilvl = lvl
numpr.NumId = lvl
para.X().PPr.NumPr = numpr
~~~

**Comment by tbaliance** [comment]
Yup, I'll add it.  I think the second part (NumId) is incorrect in your example though, it's a reference to a numbering style defined in styles.xml

**Comment by freb** [comment]
A reference to `number.xml` seems a little more legit than choosing a random int :).

Thanks, yet again.

**Comment by tbaliance** [comment]
@freb Done, check out _examples/document/simple for example usage.

To mimic what you were doing, you can do this instead:
```
para.SetNumberingLevel(level)
para.SetNumberingDefinitionByID(defnID)
```

**Comment by freb** [comment]
I think there might be an error in the implementation. I also might be wrong.

In `document.xml`, paragraphs look like look like this (second indented item):

```xml
<w:p w14:paraId="1D8F95A7" w14:textId="294F4857" w:rsidP="00BD6BD9" w:rsidR="00BD6BD9" w:rsidRDefault="00BD6BD9">
	<w:pPr>
		<w:pStyle w:val="ListOrdered"/>
		<w:numPr>
			<w:ilvl w:val="1"/>
			<w:numId w:val="2"/>
		</w:numPr>
	</w:pPr>
	<w:r>
		<w:t>List Item Text Here</w:t>
	</w:r>
</w:p>
```
In `numbering.xml`, there are `num`'s and `abstractNum`'s. Mine looks like this:

```xml
<w:abstractNum w15:restartNumberingAfterBreak="0" w:abstractNumId="0">
	...
</w:abstractNum>
<w:abstractNum w15:restartNumberingAfterBreak="0" w:abstractNumId="1">
	...
</w:abstractNum>
<w:num w:numId="1">
	<w:abstractNumId w:val="0"/>
</w:num>
<w:num w:numId="2">
	<w:abstractNumId w:val="1"/>
</w:num>

```
The `numId` value in the paragraph looks like it points to a `<w:num>`, not an `abstractNum`.

The helper methods on the paragraph, `SetNumberingDefinition` and `SetNumberingDefinitionByID` both essentially operate on a `NumberingDefinition` which is a `CT_AbstractNum`. The sets the `NumId` on the `NumPr` of the paragraph properties `PPr.NumPr.NumId`, but they set it equal to the id of the `abstractNum` that is passed in.

I believe the `PPr.NumPr.NumId` should point to a `CT_Num.NumIdAttr`which is an entry in `doc.Numbering.X().Num`. `CT_Num` then contains the reference to the `AbstractNumId` that you want to use.

I don't think the function signatures for the paragraph helpers needs to change since any lookups or creations would take place against the `abstractNum`, but the `CT_Num` would probably need to be looked up or created based on the `abstractNum` so that the `CT_Num` could then be referenced.

I noticed in my XML there are two `abstractNums` with ids `0` and `1`, but the paragraph references use IDs `1` and `2` which match the `<w:num>` tags. The naming also seems to line up.

Let me know if I have something wrong.
