### ISSUE TITLE
.doc file

### ISSUE THREAD

**Issue by smallage** [baliance/gooxml#139]
## Description
   HI, I try resolve the .doc file,the system report an error:   error opening document: parsing zip: zip: not a valid zip file 
## Expected Behavior
I hope it's ok. The .docx file is well done.  my english is  poor,I hope you can help me.
## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by tbaliance** [comment]
@smallage Unfortunately this library will never be able to read .doc files.  You'll need to convert them to .docx first, the file formats are completely different.

**Comment by smallage** [comment]
Yes, please. Thank you.

**Comment by ghc-laile** [comment]
iiiiiiiiiiiiiiiii,Why do I also have this problem with docx
==============================================================
code:
document.Open("cs.docx")
error：
error opening document: parsing zip: zip: not a valid zip file

**Comment by sampila** [comment]
Hi @ghc-laile, 

Could you share the "**docx**" file?
