### ISSUE TITLE
document table fixed columns width

### ISSUE THREAD

**Issue by ztype** [baliance/gooxml#140]
Hi,
  I create a docx file,and add some tables in it. When I open it with Office Word,the table columns' don't show the width I specified in my code.
 I find out this is because Office Word has an `Automatically resize to fit contents` option in every single table.The docx file would show properly if I disable this option in the table's properties in Office Word.
 So,I suggust if there is a way to disable such option or fix the columns width as I wish?

**Comment by tbaliance** [comment]
@ztype I added support for this that will be merged in soon.

```
table.Properties().SetLayout(wml.ST_TblLayoutTypeFixed)
```

**Comment by ztype** [comment]
great!
thx a lot
