### ISSUE TITLE
Heading Level problem

### ISSUE THREAD

**Issue by ztype** [baliance/gooxml#144]
Hi,
  I update the package today and find out a bug with Heading Level.
  This is how the `toc.docx` in `_examples` directory shows:
![hl](https://user-images.githubusercontent.com/32980712/34400510-1149fc74-ebcd-11e7-9a46-cc36377b7d51.png)

  And this is how the docx I generate with the code `_examples/toc/main.go` shows:
![hlp](https://user-images.githubusercontent.com/32980712/34400529-489a75aa-ebcd-11e7-95f4-f899e24d45da.png)
 
  As you see,the title is not at the beginning of the line as before.
  I use Office Word 2016.

**Comment by tbaliance** [comment]
@ztype Give that a shot when it's merged in a few minutes.  Feel free to re-open this issue if you need something more.
