### ISSUE TITLE
Wrong separator characters in Windows

### ISSUE THREAD

**Issue by tbaliance** [baliance/gooxml#146]
decode map should use path.Clean instead of filepath.Clean to preserve forward slashes on Windows

**Comment by AlexeyUzhva** [comment]
@tbaliance thank you a lot for noticing!

It works under windows with your commit.

Would be very grateful if you merge it back, so you can once again use your master branch in our software.

**Comment by tbaliance** [comment]
@AlexeyUzhva Done, it's in master now,

**Comment by AlexeyUzhva** [comment]
Thanks! So quick!
