### ISSUE TITLE
add superscript and subscript to RunProperties

### ISSUE THREAD

**Issue by alexkowalenko** [baliance/gooxml#151]
## Description
Add the ability to change the text formatting to superscript and subscript. 
## Expected Behavior
The text will have super and subscripts.
## Actual Behavior
There seems to be no way to do this. Can't find a function call on `RunProperties` that supports this. I imagine that it would like something like `SetBold(bool)`.

**Comment by tbaliance** [comment]
Once this is merged in, you can do something like:
```
run.Properties().SetVerticalAlignment(sharedTypes.ST_VerticalAlignRunSuperscript)
```

**Comment by alexkowalenko** [comment]
Thanks!
