### ISSUE TITLE
Presentation Error

### ISSUE THREAD

**Issue by jorgelub12** [baliance/gooxml#159]
Im using the example of PPT template but im getting this errors:

![image](https://user-images.githubusercontent.com/17097930/36410417-e6cae8d2-15de-11e8-8fd0-07ed7f440fa3.png)
![image](https://user-images.githubusercontent.com/17097930/36410425-f005104e-15de-11e8-88da-dbd57a3f90c6.png)

**Comment by tbaliance** [comment]
@jorgelub12 Sorry, I never meant to commit this.  It's not working yet, as you've found out.

**Comment by tbaliance** [comment]
@jorgelub12 Give this a shot, it works in my very minimal testing.
