### ISSUE TITLE
Unable to figure out how to set page margins on document

### ISSUE THREAD

**Issue by srinathh** [baliance/gooxml#165]
## Description
I am unable to figure out how to set page margins on document. I would like to set margins of the generated document to 0.5 inch

I managed to follow the rabbit hole of XML down to `doc.X().Body.SectPr.PgMar.TopAttr` but then there's a pointer to an int64 which i'm not able to set. When I try to retrieve the object, I get a null pointer error.

**Comment by tbaliance** [comment]
@srinathh I'll add this to my TODO to make a helper method, but for now you'll need to create the int64 yourself.  Look at this `AddTabStop` method for reference `gooxml.Int64` just creates a pointer to an int64, and the measurement stuff is used for translating distance units.

```go
  // AddTabStop adds a tab stop to the paragraph.
  func (p ParagraphStyleProperties) AddTabStop(position measurement.Distance, justificaton wml.ST_TabJc, leader w  ml.ST_TabTlc) {
          if p.x.Tabs == nil {
                  p.x.Tabs = wml.NewCT_Tabs()
          }
          tab := wml.NewCT_TabStop()
          tab.LeaderAttr = leader
          tab.ValAttr = justificaton
          tab.PosAttr.Int64 = gooxml.Int64(int64(position / measurement.Twips))
          p.x.Tabs.Tab = append(p.x.Tabs.Tab, tab)
  }
```

**Comment by srinathh** [comment]
Thanks! I've created a helper function to set margins based on your code & sent a pull request.

**Comment by tbaliance** [comment]
Great, thanks! I'll merge it soon.
