### ISSUE TITLE
Lost header and footer when I add page break

### ISSUE THREAD

**Issue by lishuu** [baliance/gooxml#173]
## Description
Hi,
When I add page break the header and footer are gone. 
run [this](https://github.com/baliance/gooxml/blob/master/_examples/document/header-footer/main.go) example

```golang
	for i := 0; i < 5; i++ {
		para = doc.AddParagraph()
		run = para.AddRun()
		run.AddText(lorem)
		
		p1 := doc.AddParagraph()
		p1.Properties().AddSection(wml.ST_SectionMarkNextPage)
	}
```
I use Office Word 2016 in windows10.
What can i do to keep header? 

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by tbaliance** [comment]
@lishuu You have to set the header on the section as well, Word doesn't automatically associate them:

```go

	for i := 0; i < 5; i++ {
		para = doc.AddParagraph()
		run = para.AddRun()
		run.AddText(lorem)

		p1 := doc.AddParagraph()
		sect := p1.Properties().AddSection(wml.ST_SectionMarkNextPage)
		sect.SetHeader(hdr, wml.ST_HdrFtrDefault)
		sect.SetFooter(ftr, wml.ST_HdrFtrDefault)
	}
```
