### ISSUE TITLE
Support Text box in word document

### ISSUE THREAD

**Issue by amanbolat** [baliance/gooxml#174]
## Description
Could not find how to get or set text box in word document.
But i found some related files on schema/soo(urn) paths.

**Comment by tbaliance** [comment]
@amanbolat Can you provide a sample document that has a text box you're trying to reproduce?

**Comment by amanbolat** [comment]
@tbaliance i created repo with one word file: https://github.com/amanbolat/gooxml-textbox-test

**Comment by tbaliance** [comment]
@amanbolat  I don't see this happening any time soon. The text box is inserted twice with an alternate content to support older versions of Word.  We round-trip these, but don't allow editing them.

Sorry, but I'm closing this for now.

**Comment by amanbolat** [comment]
@tbaliance I thought, that will be better to add function to fetch paragraphs from text box too. If it's not in roadmap then extracting textbox from Extra field and then loop through it to get paragraphs is very painful.
