### ISSUE TITLE
how to insert table somewhere?

### ISSUE THREAD

**Issue by jjjachyty** [baliance/gooxml#178]
## Description
i want to insert a table  after somewhere of Paragraph,how to do?
## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by tbaliance** [comment]
@jjjachyty See _examples/document/tables/  for a table example.  I'm not quite sure I follow your question though.

**Comment by jjjachyty** [comment]
I have seen ，but i don't find like document.insertTable(location) API，just find insertParagraphAfter(p)

**Comment by jjjabc** [comment]
@jjjachyty 你可以看看我提的pull request #181 .希望能够帮助你.我最近也需要插入一个table,遇到这个问题.

**Comment by tbaliance** [comment]
Thanks! I merged your pull request.

**Comment by jjjachyty** [comment]
@jjjabc  👍 要是有文档合并 和 转换(html)就好了
