### ISSUE TITLE
missing SetLineSpacing

### ISSUE THREAD

**Issue by CYL96** [baliance/gooxml#184]
## Description
I have append it into source go.Missing SetLineRuleSpacing too
## Expected Behavior
1.5 line = (font size )*1.5
double = (font size)*2 
chinese firstIndent 2ch =   (font size)*2 

## Actual Behavior

code:

func (p ParagraphProperties) SetLineSpacing(linespacing measurement.Distance){
	p.x.Spacing = wml.NewCT_Spacing()
	p.x.Spacing.LineAttr = &wml.ST_SignedTwipsMeasure{}
	p.x.Spacing.LineAttr.Int64=gooxml.Int64(int64(linespacing / measurement.Twips))
}

**Comment by tbaliance** [comment]
Fixed in #183
