### ISSUE TITLE
Footer for last page

### ISSUE THREAD

**Issue by mchusovlianov** [baliance/gooxml#187]
Hi, guys! Is it possible to set header/footer for the last page?

**Comment by tbaliance** [comment]
Look at the _examples/document/header-footer-multiple and see if that helps.  If not, post an example document and I'll take a look.

**Comment by mchusovlianov** [comment]
That's quite difficult as I can't create an example in Word. But I'll try to explain to you, for instance, you have a long long table in your docx file, for instance, 4-5 pages with one table. I'd like to have only one footer on the last page of the doc.

**Comment by tbaliance** [comment]
If standard Word won't do it, it won't be possible through this library either as it writes the same file format. To create multiple headers/footers, you must use different document sections.  See the _examples/document/header-footer-multiple  example and you can possible get close to what you want.
