### ISSUE TITLE
table SetWidth is not valid

### ISSUE THREAD

**Issue by mr-shaven** [baliance/gooxml#194]
In my project，

> table.Properties().SetWidth(5 * measurement.Centimeter)

but the export has no width.  when I run _examples  as same no effect.

**Comment by mr-shaven** [comment]
it's the partial result of export in _examples/document/tables  that i  opened with pages under MAC,[http://obue5kv5x.bkt.clouddn.com/WX20180816-112153@2x.png](url), it's expected in windows system.

there is another question, how to set Cell width in .xlsx files or automatically adapter the width of content?

**Comment by tzneal** [comment]
@mr-shaven It looks like Pages is just broken, it works in all of the versions of Word I've tried.  

For Cells, see:

CellStyle.SetWrapped and CellStyle.SetShrinkToFit

For cell column Widths, see Column.SetWidth

**Comment by tbaliance** [comment]
@mr-shaven It looks like Pages is just broken, it works in all of the versions of Word I've tried.

For Cells, see:

CellStyle.SetWrapped and CellStyle.SetShrinkToFit

For cell column Widths, see Column.SetWidth
