### ISSUE TITLE
unsupported relationship type

### ISSUE THREAD

**Issue by ghosttk** [baliance/gooxml#195]
## Description
When running _examples/documents/edit-document/main.go , I got these outputs.
## Expected Behavior
Yesterday it worked, but today it doesn't.
## Actual Behavior
2018/09/06 11:19:02 unsupported relationship type: http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties tgt: docProps/custom.xml
2018/09/06 11:19:02 unsupported relationship type: http://schemas.openxmlformats.org/officeDocument/2006/relationships/glossaryDocument tgt: word/glossary/document.xml
not modifying Sincerely,
not modifying To get started right away, just tap any placeholder 
not modifying text (such as this) and start typing.
not modifying Wondering what to include in your cover letter? It’s a good idea to include key points about why you’re a great fit for the company and the best choice for the specific job. Of course, don’t forget to ask for the inter
not modifying view—but keep it brief! A cover letter shouldn’t read like a novel, no matter how great a plot you’ve got.

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by tbaliance** [comment]
The warning just indicate that those files are round tripped, but we don't allow editing. I just tested and the example worked for me, are you experiencing issues with it?

**Comment by ghosttk** [comment]
Thanks, I works and the 'edit-document.docx' is generated correctly, I just ingore the two warning.
