### ISSUE TITLE
Failure parsing Word document saved from Google Docs, reproducible

### ISSUE THREAD

**Issue by preciselytom** [baliance/gooxml#196]
[Bug provocation.docx](https://github.com/baliance/gooxml/files/2371482/Bug.provocation.docx)

I created this file by opening Google Drive, selecting New, then Google Docs, writing the content (some text and a table), then File > Download as... > Microsoft Word (.docx).

Both `document.Open()` and `document.Read()` fail loading the file with this error:

```error decoding word/document.xml: parsing 9029.0 as int: strconv.ParseInt: parsing "9029.0": invalid syntax```

Indeed, the file contains, inside `word/document.xml`:

```
    <w:tbl>
      <w:tblPr>
        <w:tblStyle w:val="Table1"/>
        <w:tblW w:w="9029.0" w:type="dxa"/>
```

This seems to be the width of the table in the document. I investigated whether dotted-decimal values are legal in `w:tblW`. Apparently there are three kinds of legal values here:

1. Integer
2. Dotted-decimal value with percentage sign
3. Dotted-decimal value with unit

I conclude that this is a bug in Google Docs, but I also note that Microsoft Word can open the input file and render it properly, while gooxml does not.

I suggest that gooxml works around this by parsing decimal numbers as floats and discarding the fractional part (especially if it is zero). Is this feasible to do, or does the XML decoding process dictate that integers are parsed as integers?

**Comment by tbaliance** [comment]
@preciselytom Please give this a shot and let me know if you have any more issues.  If it works for you, I'll tag a new release in a day or so.

**Comment by preciselytom** [comment]
That fixed it, exemplary work and response time, thanks!
