### ISSUE TITLE
When edit docx file generated by pandoc, the rId in document.xml.rels may goes duplicated.

### ISSUE THREAD

**Issue by JasonFromSpace** [baliance/gooxml#198]
## Description
Fisrt of all, Thanks for your hard work to make this fantastic lib.  I use it very often in my work.

By the way, english is not my mother language. I have tried my best to make it clear :)  If I used the wrong words, please forgive me.

Open docx file generated by pandoc (from html)， add image to it and save. Open the file in office 2016, image may be wrong (where picture A should exist is picture B).  Unzip the file, open document.xml.rels, i found there are two relationship which has the same rId.

In gooxml\common\relationships.go::AddRelationship()，use "len(r.x.Relationship)+1" as the next rId aviable, but pandoc did not follow this rule, and something goes wrong. 

## Expected Behavior
When add image to an exist docx file, every thing should be fine.

## Actual Behavior
When the docx file is generated by pandoc, there may be some problem with image.

From some reason, i can't upload a demo docx file , sorry about that.

**Comment by tbaliance** [comment]
Can you email a sample file to support@baliance.com? I don't think it will be too hard to fix.

**Comment by JasonFromSpace** [comment]
A  sample docx file (in.docx) and sample code (main.go) was include in attachment.
There are 12 items in document.xml.rels, but rId of Image start at 21.


The version of pandoc is 2.0.6





At 2018-09-13 09:05:23, "Todd" <notifications@github.com> wrote:


Can you email a sample file to support@baliance.com? I don't think it will be too hard to fix.

**Comment by JasonFromSpace** [comment]
> Can you email a sample file to [support@baliance.com](mailto:support@baliance.com)? I don't think it will be too hard to fix.

I have emailed a sample file to [support@baliance.com]. In case GFW block the mail. I upload the file here too.
[issue198.zip](https://github.com/baliance/gooxml/files/2379295/issue198.zip)

**Comment by tbaliance** [comment]
Should be fixed now, let me know if you run into any more issues.

**Comment by JasonFromSpace** [comment]
> Should be fixed now, let me know if you run into any more issues.

Everything works fine now,  thanks!

**Comment by JasonFromSpace** [comment]
> Should be fixed now, let me know if you run into any more issues.

Hi,  there still have some chance to get invalid rId. Consider the case follow.
rId exist:  1 3 5 7
round 1:  expect 5,  got 1 3 5 7 6
round 2:  expect 6,  got 1 3 5 7 6 7  <-  there are two 7

the rId append is not sorted,  so may get wrong rId in some special case.

**Comment by tbaliance** [comment]
@JasonFromSpace Thanks for pointing that out, I've got a new fix that will be merged in a few minutes.
