### ISSUE TITLE
Cell Margins

### ISSUE THREAD

**Issue by sturgill** [baliance/gooxml#202]
This is likely a very simple oversight, but I promise I've read through the docs (source code as well as godoc). But how do you apply a margin to a table cell? I can add spacing to a paragraph within a cell:

```golang
para := cell.AddParagraph()
para.Properties().Spacing().SetBefore(5 * measurement.Point)
para.Properties().Spacing().SetAfter(5 * measurement.Point)
```

But I haven't found a way to add left/right margins to the cell itself.

Any guidance would be appreciated!

**Comment by tbaliance** [comment]
@sturgill Give that a shot, I accidentally pushed it directly to master instead of a branch, but I tested on my end.
