### ISSUE TITLE
How to insert row in sheet?

### ISSUE THREAD

**Issue by l0rda** [baliance/gooxml#203]
Hi,

How to insert a new row in sheet?

Tried with https://godoc.org/baliance.com/gooxml/spreadsheet#Sheet.AddNumberedRow, but no luck.

**Comment by tbaliance** [comment]
Can you paste a compilable example that fails?  Plain Row() should work:

```
wb := spreadsheet.New()
sheet := wb.AddSheet()

// Row/Cell create or returns a cell with a given reference
sheet.Row(1).Cell("A").SetNumber(1.23)
```

**Comment by l0rda** [comment]
For example, i need to insert 10 rows between 6 and 7. How to do that? Only create new sheet and copy rows? My case is filling invoice with items.
