### ISSUE TITLE
pdf generation

### ISSUE THREAD

**Issue by gedw99** [baliance/gooxml#210]
I noticed in the examples that Word and excel are needed to generate the PDF'S

This means you need a copy of work etc from Microsoft. I am wondering if Open Office can be used ?

https://wiki.openoffice.org/wiki/API/Tutorials/PDF_export

EDIT. I just realised that this is based on OPen Office, Not microsoft word or excel.
Correct ?

**Comment by gedw99** [comment]
see: https://github.com/baliance/gooxml/blob/master/_examples/document/pdf-export-ole/main.go

this really requires Word ? Cant use Open Office ?

**Comment by tbaliance** [comment]
@gedw99 It won't work with the code I provided, it uses MS's OLE to automate Word.  You might be able to use open office, it looks like it used to work from the command line anyway:

https://forum.openoffice.org/en/forum/viewtopic.php?f=5&t=83014
