### ISSUE TITLE
How to get style of cell?

### ISSUE THREAD

**Issue by l0rda** [baliance/gooxml#211]
Hi,

how to get CellStyle for a cell?

Cell has methods
`func (c Cell) SetStyle(cs CellStyle)`
`func (c Cell) SetStyleIndex(idx uint32)`

but have not **GetStyle()** or **GetStyleIndex()**.
I want to copy style from one cell to another. Or just apply same style by index.

**Comment by l0rda** [comment]
I found workaround:
```go
baseStyle := sheet.Row(1).Cell("A").X().SAttr
```

**Comment by tbaliance** [comment]
Not currently, not sure when/if I'll get around to doing this as it's not a quick fix.

**Comment by l0rda** [comment]
I hope you will add this in future.

**Comment by l0rda** [comment]
Some helpers here:
https://github.com/l0rda/gooxmlhelpers

```go
// FillColor - fill cell by reference with color and save current cell style
FillColor(ss spreadsheet.StyleSheet, cell spreadsheet.Cell, clr color.Color)
// SetNumberFormat - set number format to cell by reference and save current cell style
SetNumberFormat(ss spreadsheet.StyleSheet, cell spreadsheet.Cell, format string) 
```
