### ISSUE TITLE
QuickPart (Add img from remote server)

### ISSUE THREAD

**Issue by Cycl0pe** [baliance/gooxml#218]
Hello,

Thanks for this beautiful library.

I was wondering if its was possible to add some QuickParts in a Word document through gooxml ? More precisely, I'm interested in adding an img from a remote server.

Thanks.

Cycl0pe

**Comment by tbaliance** [comment]
@Cycl0pe That's not a very commonly used feature, so we're probably not interested in adding it.  You can always download the image and then insert it.
