### ISSUE TITLE
Document Mail Merge: fields inside tables ignored

### ISSUE THREAD

**Issue by christopher-wong** [baliance/gooxml#223]
## Description
Mail Merge fields inside tables are ignored.

https://github.com/baliance/gooxml/tree/master/_examples/document/mail-merge

## Expected Behavior
Mail merge fields inside table should be merged with data like a normal field outside a table.

## Actual Behavior
Mail merge fields inside tables are ignored.

[mm-with-table.docx](https://www.dropbox.com/s/cz0njr6kjkwope4/mm-with-table.docx?dl=0)

**Comment by tbaliance** [comment]
@christopher-wong Test this out and let me know, the mm-with-table that you provided is a newer Word format that we don't support yet so I couldn't test it myself.

**Comment by christopher-wong** [comment]
Looks like this works! I'm doing some more testing today and will follow up, but thanks for the quick turn around.
