### ISSUE TITLE
Unsupported purl.oclc.org

### ISSUE THREAD

**Issue by freb** [baliance/gooxml#241]
## Description

I'm hitting a weird issue when updating `FldChar`'s. I need to replace the default text in some form fields. If I mark the fields as `dirty` or set `SetUpdateFieldsOnOpen(true)` and then select to update the entire table as prompted when the document opens, saving the result makes it unusable by gooxml. I get the following warnings and `doc.X().Body` is `nil`:

```
2019/02/19 16:34:16 unsupported relationship type: http://purl.oclc.org/ooxml/officeDocument/relationships/officeDocument tgt: word/document.xml
2019/02/19 16:34:16 unsupported relationship type: http://purl.oclc.org/ooxml/officeDocument/relationships/extendedProperties tgt: docProps/app.xml
```

Digging through the raw XML, it doesn't look like an issue with the actual `FldChar`'s that are being altered, it looks like an issue with the document namespacing. For some reason, after updating the form fields, some of the `http://schemas.openxmlformats.org/officeDocument/2006/...` attributes get replaced with `http://purl.oclc.org/ooxml/officeDocument/...`.

I don't know enough about the spec to know why these would change. But the resulting document opens just fine with Word. It is only gooxml that has an issue.

I tried this with and without the presence of a table of contents. When the table of contents isn't present, there is no issue. When the table of contents is present, and you select "update entire table", then you experience the problem after saving the document.

## Expected Behavior

Handle documents using `purl.oclc.org` namespacing appropriately.

## Actual Behavior

Documents with `purl.oclc.org` namespacing have a nil Body.

I've attached before and after documents. The actual FldChar changes appear starting on page 11 (a result of re-using code that originally produced the issue). If you need the code making the changes or simplified before/after documents, just let me know.

[after.docx](https://github.com/baliance/gooxml/files/2882458/after.docx)
[before.docx](https://github.com/baliance/gooxml/files/2882459/before.docx)

**Comment by nkryuchkov** [comment]
Hello @freb , could you please show the code making changes?

**Comment by freb** [comment]
Here is a Gist of the code:

https://gist.github.com/freb/459528c9cf205d56614df27cc99c854d

Let me know if you have any questions about it.

**Comment by nkryuchkov** [comment]
Hello @freb , please take a look at the PR. I added the test case with your doc and processing code. I can not reproduce your issue. If I take the "after.docx" you had provided, I see the issue, the doc body is nil. But if I run your code on the "before.docx" and open the resulting doc, the doc body is there, the namespace does not seem to be changed. I am willing to help you with your issue, so please take a look at the test, maybe we are missing something

**Comment by freb** [comment]
The issue with the new test case is that the namespace issue doesn't arise until after you have opened and saved the document with Word.

When I open the after.docx document after it was just created by the gist code, I'm presented with two dialogs boxes that I must respond to in order to get the references I added to the document to display, and also produce the issue I'm describing. I'm using the latest version of Word but have not tried it on earlier versions.

Here are the dialogs and my responses:

1. The document contains fields that may refer to other files. Do you want to update the fields in this document?: (select Yes)
2. Word is updating the table of contents. Select one of the following options: (select Update entire table)

After that you must re-save the document.

After running `go run gist.go before.docx after.docx`, and then performing those three actions on after.docx, after.docx is in the state that I uploaded.

**Comment by nkryuchkov** [comment]
@freb I found out what causes the issue and I'm working on a fix. I'll create a pool request soon and let you know

**Comment by nkryuchkov** [comment]
Hello, @freb . It seems that purl.oclc.org is a namespace for the new document format. I believe that Word is kind of migrating the document schema to stick to the new one. This namespace describes doc structure really similar to the "http://schemas.openxmlformats.org/officeDocument/2006/..." one. I am working now on adding the "purl.oclc.org" support to the library. This way you will be able to open the documents with any of these schemas without worrying for Word to change anything and make file unprocessable.

**Comment by freb** [comment]
Thanks for the update. I'm glad you were able to figure it out and are making progress.

**Comment by nkryuchkov** [comment]
Hello, @freb . I am almost finished with this issue, both of the documents you had provided can be opened with the library. Before I create a PR with this, is there any chance that you have more of the documents with this "purl.oclc.org" namespace? I would like to test the code properly

**Comment by freb** [comment]
That's the only one I have that I know of. I could generate more, but I would just use the same method as the first, so I'm not sure that would be helpful.

**Comment by gunnsth** [comment]
@freb When you save the file in Word. Do you specifically select to save the file in format "Strict Open XML format (\*.docx)"  rather than "Word Document (\*.docx)" ?

When I open after.docx I did not get any prompt about updating content, but clicking Save As, the strict option seems to come up by default.

For before.docx the default save option is "Word Document (\*.docx)".

**Comment by freb** [comment]
@gunnsth I don't specifically select to save the document as "Strict Open XML format". After opening the document, I did a `Save`, not a `Save As`.

However, that is a good point you brought up. I just reviewed this and it turns out that after updating fields, it automatically changes the save type to `Strict Open XML format (*.docx)` so that when you save it, Strict is the new filetype. If do a `Save As` and change it back to `Word Document (*.docx)`, it changes the schema back, and gooxml can read it again.

**Comment by gunnsth** [comment]
@freb We've been working on this issue quite a bit.  PR #265 implements the purl.oclc.org namespace such that gooxml can read those strict files.  Can you take a look at the PR and test?

We have not found out why Word chooses to save the files in the strict format. It seems to happen even if a single field is updated with the code that you provided.

**Comment by freb** [comment]
I just tested the PR with my example documents and it appears to work as expected.
