### ISSUE TITLE
[QUESTION]How do I center the table cell

### ISSUE THREAD

**Issue by CR903** [baliance/gooxml#249]

**Comment by freb** [comment]
Do you mean center the text horizontally within the cell? You do this on the paragraph properties:

```go
para.Properties().SetAlignment(wml.ST_JcCenter)
```

If you mean center it vertically, you use the cell properties:

```go
cell.Properties().SetVerticalAlignment(wml.ST_VerticalJcCenter)
```

**Comment by gunnsth** [comment]
This (and many other useful cases) is shown in the examples too:
https://github.com/baliance/gooxml/blob/32d0f798930b92a15044b3a566a889a3eac3ca88/_examples/document/tables/main.go#L93
