### ISSUE TITLE
Access Nested Tables

### ISSUE THREAD

**Issue by freb** [baliance/gooxml#256]
## Description

I have a word document that was provided to me as a template. I decided to walk the unaltered document and insert bookmarks in various locations in order to keep track of them. I noticed some bookmarks were not being found, so I submitted PR #255. While working on that, I noticed that tables can be nested and so I wrote the code to account for that.

After implementing that, I realized that once I have a list of bookmarks, I want to fetch the containing element so that I can work with its contents (either a paragraph or a cell). This is where I ran into an issue.

When I drop down to the underlying data structures using `.X()`, I don't have a way of using what I find to then construct the more convenient structs--`document.Paragraph`, `document.Cell`, etc. For example, If I find the `*wml.Ct_Tc` that contains the bookmark, I can't turn that into a `document.Cell`.

My solution was to just walk the document again and compare pointers between the `*wml.Ct_Tc` that I discovered and the `document.Cell.X()` that I was comparing it to.

This approach worked well until I discovered that the [document.Tables](https://github.com/baliance/gooxml/blob/master/document/document.go#L339) function does not iterate nested tables. So In Word you can created nested tables and place bookmarks in them, and the bookmark retrieval code updated with PR #255 will find the bookmarks, but you cannot actually obtain or construct the `document.Table` object for the table containing the bookmark.

## Expected Behavior

There are two solutions:

**1.** You can create some helper functions to allow for the construction of convenience structs (`document.Cell`, `document.Paragraph`, etc.). This would allow anyone with the right fields obtained from `.X()` calls to turn them into the more helpful objects. Of course this could cause some problems if used in the wrong way. But this is probably my prefered approach since it would eliminate the need to loop every block and run element in the document whenever I want to locate something.

**2.** You could adjust the functionality of the `document.Tables()` function to include nested tables. This is arguably the correct behavior of the function, though it could break someones code.

**Comment by gunnsth** [comment]
@freb Did #257 and #255 address all of those?

**Comment by freb** [comment]
Yes, I'll close this.
