### ISSUE TITLE
Tls Issue

### ISSUE THREAD

**Issue by Sathyavathi2018** [baliance/gooxml#270]
# Description
Followed https://github.com/baliance/gooxml#installation.

# Expected Behavior
The package was fetched and added to my gopath.

# Actual Behavior 
  We are suddenly receiving below error while compilation:

The following errors occurred while deducing packages:
  * "baliance.com/gooxml/schema/soo/wml": unable to deduce repository and source type for "baliance.com/gooxml/schema/soo/wml": unable to read metadata: unable to fetch raw metadata: failed HTTP reque
st to URL "http://baliance.com/gooxml/schema/soo/wml?go-get=1": Get https://baliance.com:443/gooxml/schema/soo/wml?go-get=1: remote error: tls: internal error

Can someone please check this and respond?

**Comment by boloboloda** [comment]
I have the same problem.
go version 1.12.

**Comment by Soontao** [comment]
Same issue, seems SSL cert error

**Comment by gunnsth** [comment]
@Soontao  @Sathyavathi2018  Should be fixed.  Please try again.

**Comment by Soontao** [comment]
Nice, build passed. 
Thanks for your help. :)

**Comment by Sathyavathi2018** [comment]
Thanks for the quick fix. Issue is resolved now.
