### ISSUE TITLE
It's Office Open XML not OpenOffice

### ISSUE THREAD

**Issue by tealeg** [baliance/gooxml#39]
## Description
Your Readme describes this as a library for OpenOffice, but it's actually a library for Office Open XML.  Most people would associate "OpenOffice" with OpenOffice.org or it's fork, LibreOffice.  Both of those suites can read these files, but have a different native file format.

## Expected Behavior
It should say "Office Open XML"

## Actual Behavior
It says "OpenOffice"

**Comment by tbaliance** [comment]
Ah, thanks, PR up.  I tend to make that mistake sometimes, Office Open doesn't roll off the tongue like Open Office.

**Comment by tbaliance** [comment]
Merged.
