### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by joeblew99** [baliance/gooxml#52]
I was thinking that with all the work you have done it may be easy to build a web GUI that can display the documents and even edit them.

Gopherjs can be used to run the golang in the web browser. 
For display I don't know how easy it will be to display a document but I don't think it has to be an exact representation. 

Quill and other libraries would also help

**Comment by tbaliance** [comment]
I try to avoid web stuff if I can help it, but if you do it let me know and I'll add a link to it from the README.

**Comment by joeblew99** [comment]
https://github.com/quilljs/delta

this is the quill format. Just need to write a mapper for ooxml. I bet there is one out there

**Comment by tbaliance** [comment]
Closing this for now, I don't expect to work on it.
