### ISSUE TITLE
Failure to parse DOCX in "use-template" example (and other simple LibreOffice created DOCX files)

### ISSUE THREAD

**Issue by zhibek** [baliance/gooxml#82]
## Description
Running the "use-template" example in the repository results in an error parsing the DOCX template included as an example (template.docx). Similarly, creating a new DOCX in LibreOffice with a single line of text also results in a parse error.

## Expected Behavior
Running the "use-template" example (or any other script using `document.OpenTemplate()` or `document.Open()` should result in a DOCX created in a standard way using an application like LibreOffice being parsed correctly.

## Actual Behavior
The following error is displayed:
```
error opening Windows Word 2016 document: error decoding docProps/core.xml: xml: invalid tag in field Attrs of type gooxml.any: ",any,attr"
```

To reproduce the problem, run the following example:
https://github.com/baliance/gooxml/blob/master/_examples/document/use-template/main.go

A DOCX exhibiting this behaviour is available here:
https://github.com/baliance/gooxml/blob/master/_examples/document/use-template/template.docx

**Comment by tbaliance** [comment]
@zhibek Sorry, I'll update the README to mention the version of Go required.  The package requires go 1.8+ due to using the ",any,attr" to help round-trip extra stuff that Word throws in. This was added to Go 1.8 as part of https://github.com/golang/go/issues/3633

Can you retry with Go 1.8 and let me know?

**Comment by tbaliance** [comment]
@zhibek I also just added a compile time constraint in #84 that will prevent gooxml from compiling with pre-go1.8.

**Comment by zhibek** [comment]
@tbaliance Thanks for looking at this.

I can confirm this is working after I changed to Go v1.8.
