### ISSUE TITLE
fails to handle images 

### ISSUE THREAD

**Issue by joeblew99** [baliance/gooxml#96]
## Description

I am takes a basic google doc and exporting it as word and then doing a basic find replace and then uploading it back into google docs.

## Expected Behavior

doc opens in google docs

## Actual Behavior

doc will not open in google docs

i am manually downloading it from google docs as a word doc which is the default for google docs.
After it spits out the Test-out.docx, i manual drag it into google drive.

````

// Copyright 2017 Baliance. All rights reserved.

package main

import (
[Test.docx](https://github.com/baliance/gooxml/files/1342384/Test.docx)

	"fmt"
	"log"

	"baliance.com/gooxml/document"
)

func main() {
	doc, err := document.Open("Test.docx")
	if err != nil {
		log.Fatalf("error opening document: %s", err)
	}

	paragraphs := []document.Paragraph{}
	for _, p := range doc.Paragraphs() {
		paragraphs = append(paragraphs, p)
	}

	// This sample document uses structured document tags, which are not common
	// except for in document templates.  Normally you can just iterate over the
	// document's paragraphs.
	for _, sdt := range doc.StructuredDocumentTags() {
		for _, p := range sdt.Paragraphs() {
			paragraphs = append(paragraphs, p)
		}
	}

	for _, p := range paragraphs {
		for _, r := range p.Runs() {
			switch r.Text() {
			case "Test":
				// ClearContent clears both text and line breaks within a run,
				// so we need to add the line break back
				r.ClearContent()
				r.AddText("Test-BG ")
				r.AddBreak()
			case "This file is used to test the translation.":
				r.ClearContent()
				r.AddText("This file is used to test the translation-BG.")

			default:
				fmt.Println("not modifying", r.Text())
			}
		}
	}

	doc.SaveToFile("Test-out.docx")
}


````
[Test.docx](https://github.com/baliance/gooxml/files/1342386/Test.docx)

**Comment by joeblew99** [comment]
If your curious on the fix, i tried this and it worked perfectly for the use case

https://github.com/nguyenthenguyen/docx

**Comment by tbaliance** [comment]
@joeblew99 That package unpacks the XML and does a search and replace.  This one fully parses the documents to allow more advanced editing.  The problem with this one is we aren't handling the image filename correctly. In the document it's 'word/media/image2.png', even though it's the only image and when saving we are writing it back out as 'word/media/image1.png' without changing the relationship file to reflect the new name.  It should be a straight forward fix, we handle the renames for other types but skipped it for images so far.

**Comment by tbaliance** [comment]
@joeblew99 I rolled a quick fix into a branch I was about to merge in.  I'l add a test for it later, but this should fix your issue. Feel free to re-open if you still run any problems.

**Comment by tbaliance** [comment]
@joeblew99 Also, do you mind if I check your test.docx in and use it as a test file?

**Comment by joeblew99** [comment]
yep you can use that file :)
thank for this..
